server:
  port: 8090

spring:
  application:
    name: payment-service
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      host: 10.20.100.117
      port: 27017
      database: mongodb_test

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    org.springframework.web: error
    com.conects.billing: debug
    jdbc.sqlonly: off
    jdbc.resultsettable: info
    jdbc.audit: off
    jdbc.sqltiming: info
    jdbc.resultset: off
    jdbc.connection: off

datasource:
  master:
    jdbcUrl: jdbc:mysql://10.20.100.117:3306/groupware?useUnicode=true&characterEncoding=UTF-8
    username: groupware
    password: groupware12#
  slave:
    jdbcUrl: jdbc:mysql://10.20.100.117:3306/callsales?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: stcompany
